# Generated by Django 3.2.9 on 2021-12-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('final_amount', models.FloatField()),
                ('payment_id', models.TextField(null=True)),
                ('rzp_order_id', models.CharField(max_length=255, null=True)),
                ('rzp_signature', models.TextField(null=True)),
                ('products', models.ManyToManyField(related_name='products', to='products.Product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='orders.status')),
            ],
        ),
    ]
